// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.AirlineLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Datum[] Data { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Alias")]
        public string Alias { get; set; }

        [JsonProperty("IATA")]
        public string Iata { get; set; }

        [JsonProperty("ICAO")]
        public string Icao { get; set; }

        [JsonProperty("Callsign")]
        public string Callsign { get; set; }

        [JsonProperty("Country")]
        public string Country { get; set; }
    }
}
